In [2]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_csv("D:/Ph.D Work/Ph.D Work Related/Thesis Writing Work/DataSet Work/crop_prediction.csv")

In [4]:
dataset

,Area,Yield,Soil_type:_Blacksoil,Soil_type:_RedSoil,Soil_type:_red_earths_with_loamy_sub_soils,Soil_type:_Deltaic_alluvial_soils,Soil_type:_northern_lights_soils,Soil_type:_Coastal_alluvial_soils,Soil_type:_Skeletal_Soils,Crop:_Rice_Swarna_MTU7029,Crop:_Rice_Chaitanya_MTU2067,Crop:_Turmeric,Crop:_Sugarcane,y
0,598400,217000,0,1,0,0,0,0,0,0,1,1,0,0
1,453200,227900,0,0,0,0,0,1,0,0,1,1,0,0
2,498300,190900,0,0,0,0,0,1,0,0,1,1,0,0
3,518700,160800,0,1,0,0,0,0,0,0,1,1,0,0
4,528900,175000,0,1,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340,41700,61400,0,0,0,1,0,0,0,1,0,0,1,0
1341,34100,58500,0,0,0,1,0,0,0,1,0,0,1,0
1342,36100,64600,0,0,1,0,0,0,0,1,0,0,1,0
1343,34500,30700,0,0,0,1,0,0,0,1,0,0,1,0
1344,29100,26800,0,0,0,1,0,0,0,1,0,0,1,0

In [5]:
dataset.describe()

,Area,Yield,Soil_type:_Blacksoil,Soil_type:_RedSoil,Soil_type:_red_earths_with_loamy_sub_soils,Soil_type:_Deltaic_alluvial_soils,Soil_type:_northern_lights_soils,Soil_type:_Coastal_alluvial_soils,Soil_type:_Skeletal_Soils,Crop:_Rice_Swarna_MTU7029,Crop:_Rice_Chaitanya_MTU2067,Crop:_Turmeric,Crop:_Sugarcane,y
count,1345.000000,1345.000000,1345.000000,1345.000000,1345.000000,1345.000000,1345.000000,1345.000000,1345.000000,1345.000000,1345.000000,1345.000000,1345.000000,1345.0
mean,63510.949442,48704.450558,0.002974,0.263197,0.221561,0.347212,0.028996,0.130112,0.005948,0.892193,0.698885,0.328625,0.385130,0.0
std,108850.275827,63579.918975,0.054473,0.440532,0.415452,0.476261,0.167858,0.336551,0.076922,0.310251,0.458913,0.469888,0.486807,0.0
min,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,6200.000000,3300.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0
50%,25400.000000,24700.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.0
75%,63600.000000,68600.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0
max,726300.000000,406000.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

In [11]:
# Split the data into features and target
X = dataset.drop("Soil_type:_Blacksoil", axis=1)
y = dataset["Crop:_Rice_Swarna_MTU7029"]

In [12]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [28]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def fit_model(algorithm, X_train, y_train):
  """
  Fits a classification model to the training data.
  """
  # Initialize the model
  if algorithm == "Logistic Regression":
    model = LogisticRegression()
  elif algorithm == "K-Nearest Neighbors":
    model = KNeighborsClassifier()
  elif algorithm == "Decision Tree":
    model = DecisionTreeClassifier()
  elif algorithm == "Random Forest":
    model = RandomForestClassifier()
  elif algorithm == "Naive Bayes":
    model = GaussianNB()
    
  # Fit the model to the training data
  model.fit(X_train, y_train)
  
  return model

# Load dataset
df=pd.read_csv("D:/Ph.D Work/Ph.D Work Related/Thesis Writing Work/DataSet Work/crop_prediction.csv")

# Split dataset into features (X) and labels (y)
X = df.drop("Soil_type:_Blacksoil", axis=1)
y = df["Crop:_Rice_Swarna_MTU7029"]

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Initialize a dictionary to store the results of the model comparisons
results = {}

# Define a list of classification algorithms to compare
algorithms = ["Logistic Regression", "K-Nearest Neighbors", "Decision Tree", "Random Forest", "Naive Bayes"]

# Iterate over the list of algorithms
for algorithm in algorithms:
  
  # Fit the model to the training data
  model = fit_model(algorithm, X_train, y_train)
  
  # Make predictions on the test data
  y_pred = model.predict(X_test)
  
  # Calculate and store the metrics for the model
  accuracy = accuracy_score(y_test, y_pred)
  precision = precision_score(y_test, y_pred)
  recall = recall_score(y_test, y_pred)
  f1 = f1_score(y_test, y_pred)
  
  # Store the results in the dictionary
  results[algorithm] = {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}

# Print the results
for algorithm, metrics in results.items():
  print(f"Results for {algorithm}:")
  print(f"Accuracy: {metrics['accuracy']}")
  print(f"Precision: {metrics['precision']}")
  print(f"Recall: {metrics['recall']}")
  print(f"F1: {metrics['f1']}")

Results for Logistic Regression:
Accuracy: 0.895910780669145
Precision: 0.9182879377431906
Recall: 0.9711934156378601
F1: 0.9440000000000001
Results for K-Nearest Neighbors:
Accuracy: 0.9070631970260223
Precision: 0.9192307692307692
Recall: 0.9835390946502057
F1: 0.9502982107355864
Results for Decision Tree:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1: 1.0
Results for Random Forest:
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1: 1.0
Results for Naive Bayes:
Accuracy: 0.8921933085501859
Precision: 0.9147286821705426
Recall: 0.9711934156378601
F1: 0.9421157684630739

C:\Users\Srikanth.Mandela\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)